server:
  port: 0

spring:
  application:
    name: product-service
  #콘솔 사용하며, 웹에서 접근을 허용하고 path는 h2-console
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    generate-ddl: true
  #자동 DB생성
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb

eureka:
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

#logging:
#  level:
#    com.gaiga.productservice: DEBUG

greeting:
  message: Welcome to the Simple E-commerce (Product Service)